# Dev → Run dependencies only, Modulith is started by IDE
version: '3'
services:

  mongo:
    container_name: t2-mongo
    image: bitnami/mongodb:7.0
    ports:
      - "27017:27017"

  postgres:
    container_name: t2-postgres
    image: postgres:12.17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  creditinstitute:
    container_name: t2-creditinstitute
    image: t2project/creditinstitute:main
    ports:
      - "8087:8080"
    environment:
      OPENTRACING_JAEGER_ENABLED: false
