# Dev profile (databases have to be started locally)
server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/data
      database: data
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

t2:
  cart:
    TTL: 0
    taskRate: 0
  inventory:
    size: 25
    TTL: 0
    taskRate: 0
  payment:
    provider:
      enabled: true
      timeout: 5
      dummy:
        url: http://localhost:8087/pay
  computation-simulator:
    enabled: false
    pi:
      totalPoints: 100000000 # 100000000 → ~5 sec; 1000000000 → ~1 min

logging:
  level:
    de.unistuttgart.t2: DEBUG
