# Prod profile (e.g. for a deployment with Docker Compose or K8s)
server:
  port: 8080

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  metrics:
    tags:
      application: modulith-backend
    distribution:
      percentiles:
        all: 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always

logging:
  level:
    de.unistuttgart.t2: INFO
