# Dev profile (databases have to be started locally)
server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/data
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

t2:
  cart:
    TTL: 0
    taskRate: 0
  inventory:
    size: 25
    TTL: 0
    taskRate: 0
  payment:
    provider:
      timeout: 5
      dummy:
        url: http://localhost:8087/pay
