# Local profile
server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/data

t2:
  cart:
    TTL: 0
    taskRate: 0

management:
  endpoints:
    web:
      exposure:
        include: health, modulith
    health:
      show-details: always
