spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:27017/data
  jpa:
    generate-ddl: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

t2:
  cart:
    TTL: ${T2_CART_TTL}
    taskRate: ${T2_CART_TASKRATE}
  inventory:
    size: ${INVENTORY_SIZE}
    TTL: ${T2_INVENTORY_TTL}
    taskRate: ${T2_INVENTORY_TASKRATE}
