# Default profile (some values will be overwritten by other profiles)
info:
  app:
    version: '@project.version@'

spring:
  data:
    rest:
      detection-strategy: annotated
    mongodb:
      uri: mongodb://${MONGO_HOST}:27017/data
      database: data
  jpa:
    open-in-view: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

t2:
  cart:
    TTL: ${T2_CART_TTL:0}
    taskRate: ${T2_CART_TASKRATE:0}
  inventory:
    size: ${T2_INVENTORY_SIZE:0}
    TTL: ${T2_INVENTORY_TTL:0}
    taskRate: ${T2_INVENTORY_TASKRATE:0}
  payment:
    provider:
      enabled: ${T2_PAYMENT_PROVIDER_ENABLED:true}
      timeout: ${T2_PAYMENT_PROVIDER_TIMEOUT:5}
      dummy:
        url: ${T2_PAYMENT_PROVIDER_DUMMY_URL}
  computation-simulator:
    enabled: ${T2_COMPUTATION_SIMULATOR_ENABLED:false}
    pi:
      totalPoints: ${T2_COMPUTATION_SIMULATOR_PI_TOTAL_POINTS:100000000} # 100000000 → ~5 sec; 1000000000 → ~1 min
