name: build and push docker image
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docker-compose*'
      - 'k8s/*'

jobs:
  dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: check out modulith
      uses: actions/checkout@v4
      with:
        path: './modulith'
    - name: set up jdk
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Maven build modulith
      run: cd modulith && ./mvnw clean install
    - run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Docker build and push (manual)
      run: |
        echo ${{ env.RELEASE_VERSION }}
        cd modulith
        docker build -t t2project/modulith:${{ env.RELEASE_VERSION }} .
        docker push t2project/modulith:${{ env.RELEASE_VERSION }}
